name = "example"
perm = "default"
rows = 3
title = "<light_purple>BungeeGUI"
empty = "GREEN_STAINED_GLASS_PANE"
sound = "ENTITY_ARROW_HIT_PLAYER"
emptysound = "ENTITY_PLAYER_LEVELUP:1:1"
commands = [
  "rules",
  "version",
  "plugins",
  "help",
  "pl"
]

[items]
[items.13]
material = "OAK_SIGN"
stack = 1
name = "<light_purple>BungeeGUI"
lore = [
  "<yellow>A Bungee Side GUI",
  "<yellow>For all your servers"
]
enchanted = true
commands = [
  "psudo= I love BungeeGUI"
]